<a href="https://colab.research.google.com/github/sowmR/ML-LinearRegression/blob/main/LinearRegression_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
dataset = pd.read_csv('./sample_data/insurance_costs.csv')
print(dataset.shape)
print(dataset.columns)

(1338, 6)
Index(['Unnamed: 0', 'age', 'sex', 'children', 'region', 'charges'], dtype='object')


In [ ]:
dataset.drop('Unnamed: 0', axis=1,inplace=True)
features = list(dataset.columns)
target = 'charges'
print(features)
print(dataset.head(5))


['age', 'sex', 'children', 'region', 'charges']
   age     sex  children     region      charges
0   19  female         0  southwest  16884.92400
1   18    male         1  southeast   1725.55230
2   28    male         3  southeast   4449.46200
3   33    male         0  northwest  21984.47061
4   32    male         0  northwest   3866.85520


# Data Preprocessing

In [ ]:
dataset = pd.get_dummies(dataset)
dataset.head(5)

age  children  ...  region_southeast  region_southwest
0   19         0  ...                 0                 1
1   18         1  ...                 1                 0
2   28         3  ...                 1                 0
3   33         0  ...                 0                 0
4   32         0  ...                 0                 0

[5 rows x 9 columns]

# Data Analysis

Analyse the data to understand the relation between features and target. 

In [ ]:
# import seaborn as sns
# sns.pairplot(dataset,hue='charges')

In [ ]:
targetData = list(dataset[target])
featureDf =  dataset.copy()
featureDf.drop(target,axis=1, inplace=True)
featureDf.shape

(1338, 8)

In [ ]:
featureData = featureDf.values
x_train = featureData[:900]
y_train = targetData[:900]
x_test = featureData[1000:]
y_test = targetData[1000:]
print(len(x_train), len(y_train))
print(x_train[:5])

900 900
[[19  0  1  0  0  0  0  1]
 [18  1  0  1  0  0  1  0]
 [28  3  0  1  0  0  1  0]
 [33  0  0  1  0  1  0  0]
 [32  0  0  1  0  1  0  0]]


In [ ]:
# Default parameters
learning_rate = 0.0003
epochs = 5

# Model 3: Linear Regression with scikit-learn model

In [ ]:
from sklearn.linear_model import  LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
print(model.coef_)
print(model.intercept_)

[ 277.38036965  460.20339923 -470.72941369  470.72941369  325.34924273
 -952.87607029 1604.92220646 -977.3953789 ]
1617.8713444742498


In [ ]:
model3_err =mean_squared_error(y_test,y_pred)
print("MSE: ",mean_squared_error(y_test,y_pred))

MSE:  147475402.23093522
